import numpy as np
from tabulate import tabulate

from geco.src import AbstractGECO
import torch
import vec2text


class ExponentialGECO(AbstractGECO.Obfuscator):
    """
    Exponential-based GECO obfuscator.
    -------------------------
    Extends the AbstractGECO Obfuscator class and implements the exponential mechanism for selecting queries based on the hypothesis generated by vec2text models.

    The main steps of the GECO mechanism are as follows:
    1. Encode the input text into an embedding using a sentence transformer model.
    2. Use n rounds of generation to produce different hypothesis for the input text using a vec2text model.
    3. Collect the generated hypothesis and use the exponential mechanism to select a query obfuscated.
    
    """
    def __init__(self, **kwargs):
        """
        Initialisation of the GECO obfuscator Abstract class. 
        
        WARNING: this is an abstract class and should not be instantiated directly. It is meant to be subclassed by specific implementations of the GECO mechanism that may use different models or configurations.

            :param log: logger to use for logging the initialization process.
            :type log: logging.Logger
            :param st_model_name: the name or path of the sentence transformer model to use for embedding the texts. This model will be used to encode both the input texts and the queries in the pool into embeddings. The embeddings will be used in the exponential mechanism to select a query and in the corrector model to reconstruct the obfuscated text.
            :type st_model_name: str
            :param inversion_model_name: the name or path of the vec2text inversion model to use for reconstructing the obfuscated text from the selected query embedding. This model will be used in the generation step of the GECO mechanism to generate a new text from the embedding of the selected query.
            :type inversion_model_name: str
            :param corrector_model_name: the name or path of the vec2text corrector model to use for reconstructing the obfuscated text from the selected query embedding. This model will be used in the generation step of the GECO mechanism to generate a new text from the embedding of the selected query.
            :type corrector_model_name: str
            :param cache_path_pins: the file path where the embeddings of the query pool will be cached. This is used to speed up the initialization process by avoiding re-encoding the queries in the pool every time the GECO class is instantiated. If the cache file exists and contains embeddings for the same number of queries as the loaded pool, it will be loaded directly. Otherwise, the queries will be re-encoded andthe cache will be updated.
            :type cache_path_pins: str
            :param collection_name: the name ofthe collection to load queries from. Defaults to "msmarco-passage/train". This collection should be compatible withthe ir_datasets library and should contain a set of queries that will be used asthe pool forthe exponential mechanism. The queries will be embedded usingthe sentence transformer model and used for selection inthe obfuscation process.
            :type collection_name: str, optional
            :param epsilons: a list of epsilon values to use for obfuscation. This is not used directly in the initialization but can be stored for reference or used in specific implementations of the GECO mechanism that may want to precompute certain values based on the epsilon values. Defaults to a list of common epsilon values used in differential privacy.
            :type epsilons: List[float], optional
            :param kwargs: additional keyword arguments, such as top_percentile and encode_batch_size, which can be used to configurethe behavior ofthe GECO mechanism. top_percentile determinesthe percentile threshold for filtering candidates inthe exponential mechanism based on their utility, and encode_batch_size determinesthe batch size to use when encodingthe queries inthe pool, which can affectthe speed and memory usage ofthe encoding process.
            :type kwargs: additional keyword arguments  

        """
        
        super().__init__(**kwargs)
        self.utility_function = 'exponential'
        self._utility_fn = self._compute_utility
        self.global_sensitivity = 2  # The global sensitivity for the exponential mechanism is 2 since we will use the cosine similarity as utility function to get the hypothesis
        self.log.info(f"ExponentialGECO Obfuscator initialized with utility function: {self.utility_function} and global sensitivity: {self.global_sensitivity}.")

    def __str__(self):
        COL1, COL2 = 22, 60
        def row(label, value):
            return [f"{label:<{COL1}}", f"{str(value):<{COL2}}"]

        model_section: str = tabulate(
            [
                row("📡  Logger",          self.log.handlers[0].baseFilename),
                row("🧠  ST Model",       self.st_model_name),
                row("🔄  Inversion Model", self.inversion_model_name),
                row("🔧  Corrector Model", self.corrector_model_name),
                row("📁  Cache Path Pins", self.cache_path_pins),
                row("📚  Collection Name", self.collection_name),
                row("🔐  Epsilons",       self.epsilons),
                row("📊  Top Percentile", self.top_percentile),
                row("🔢  Encode Batch Size", self.encode_batch_size),
            ],
            headers=[f"{'Parameter':<{COL1}}", f"{'Value':<{COL2}}"],
            tablefmt="rounded_outline",
        )
        return "\n".join([
            "🔒  GECO Obfuscator  (ExponentialGECO)\n",
            model_section
        ])
    
    def _compute_utility(self, query_embedding) -> torch.Tensor:
        """Compute the utility of a query embedding based on the exponential mechanism.

        The utility is computed as the cosine similarity between the query embedding and the input text embedding, which is used as the hypothesis in the exponential mechanism. The cosine similarity is a common choice for measuring the similarity between two embeddings in high-dimensional space, and it ranges from -1 (completely dissimilar) to 1 (identical). In the context of the exponential mechanism, we can use the cosine similarity directly as the utility function, since it captures how well the query embedding matches the input text embedding.

        :param query_embedding: the embedding of a query for which we want to compute the utility against the input text embedding.
        :type query_embedding: torch.Tensor

        :return: a utility value corresponding to the input query embedding, where the utility is computed based on the cosine similarity between the query embedding and the input text embedding.
        :rtype: torch.Tensor

        """
        # Compute cosine similarity
        cosine_sim = torch.nn.functional.cosine_similarity(query_embedding.cpu(), self.input_embedding.cpu(), dim=0)
        return cosine_sim
    
    def obfuscate(self, text, epsilon, seed = None, n_steps=50):
        """TODO:

        """
    
        # Step 1: Encode the input text into an embedding
        embedding = self.embed(text)

        # Step 2: Reconstruct from the embedding using the inversion model to get the hypothesis
        device = next(self.corrector.model.parameters()).device
        with torch.no_grad():
            output_string, candidates = vec2text.invert_embeddings(
                embeddings=embedding.unsqueeze(0).to(device),
                corrector=self.corrector,
                num_steps=n_steps,
                sequence_beam_width=8
            )
        for i in range(len(candidates)):
            print(f"Step {i+1} candidates: {candidates[i]}")
            print(f"Step {i+1} output string: {output_string[i]}")
        exit()
        return output_string[0]
    
